services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SocialDataBundle\Command\FetchSocialPostsCommand:
        tags:
            - { name: console.command }