services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SocialDataBundle\Controller\:
        resource: '../../src/Controller'
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']