services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SocialDataBundle\Manager\ConnectorManagerInterface: '@SocialDataBundle\Manager\ConnectorManager'
    SocialDataBundle\Manager\ConnectorManager:
        arguments:
            $availableConnectors: '%social_data.connectors.available%'

    SocialDataBundle\Manager\LogManagerInterface: '@SocialDataBundle\Manager\LogManager'
    SocialDataBundle\Manager\LogManager: ~

    SocialDataBundle\Manager\WallManagerInterface: '@SocialDataBundle\Manager\WallManager'
    SocialDataBundle\Manager\WallManager: ~

    SocialDataBundle\Manager\SocialPostManagerInterface: '@SocialDataBundle\Manager\SocialPostManager'
    SocialDataBundle\Manager\SocialPostManager: ~

    SocialDataBundle\Manager\FeedPostManagerInterface: '@SocialDataBundle\Manager\FeedPostManager'
    SocialDataBundle\Manager\FeedPostManager: ~
