services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SocialDataBundle\Registry\ConnectorDefinitionRegistryInterface: '@SocialDataBundle\Registry\ConnectorDefinitionRegistry'
    SocialDataBundle\Registry\ConnectorDefinitionRegistry: ~