social_data_connector_facebook_connect:
    path: /admin/social-data/connector/facebook/connect
    defaults: { _controller: SocialDataBundle\Controller\Admin\Connector\FacebookController::connectAction }

social_data_connector_connect_check:
    path: /admin/social-data/connector/facebook/check
    defaults: { _controller: SocialDataBundle\Controller\Admin\Connector\FacebookController::checkAction }