SocialDataBundle\Model\Feed:
    type: entity
    table: social_data_feed
    fields:
        id:
            type: integer
            id: true
            column: id
            generator:
                strategy: AUTO
        publishPostImmediately:
            column: publish_post_immediately
            nullable: false
            type: boolean
            unique: false
        persistMedia:
            column: persist_media
            nullable: false
            type: boolean
            unique: false
        configuration:
            column: configuration
            type: object
            nullable: true
        creationDate:
            column: creation_date
            type: datetime
            nullable: false
    manyToOne:
        connectorEngine:
            targetEntity: SocialDataBundle\Model\ConnectorEngine
            joinColumn:
                name: connector
                referencedColumnName: id
                onDelete: CASCADE
        wall:
            targetEntity: SocialDataBundle\Model\Wall
            inversedBy: feeds
            joinColumn:
                name: wall
                referencedColumnName: id
                onDelete: CASCADE
    manyToMany:
        feedTags:
            targetEntity: SocialDataBundle\Model\Tag
            cascade:
                - persist
            joinTable:
                name: social_data_feed_tags
                joinColumns:
                    feed_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
                        nullable: false
                        onDelete: CASCADE