SocialDataBundle\Model\LogEntry:
    type: entity
    table: social_data_log
    fields:
        id:
            type: integer
            id: true
            column: id
            generator:
                strategy: AUTO
        type:
            column: '`type`'
            nullable: false
            type: string
        message:
            column: message
            nullable: false
            type: text
        creationDate:
            column: creation_date
            type: datetime
            nullable: false
    manyToOne:
        connectorEngine:
            targetEntity: SocialDataBundle\Model\ConnectorEngine
            orphanRemoval: true
            joinColumn:
                name: connector_engine
                referencedColumnName: id
                onDelete: CASCADE
        wall:
            targetEntity: SocialDataBundle\Model\Wall
            orphanRemoval: true
            joinColumn:
                name: wall
                referencedColumnName: id
                onDelete: CASCADE
        feed:
            targetEntity: SocialDataBundle\Model\Feed
            orphanRemoval: true
            joinColumn:
                name: feed
                referencedColumnName: id
                onDelete: CASCADE
