SocialDataBundle\Model\Wall:
    type: entity
    table: social_data_wall
    fields:
        id:
            type: integer
            id: true
            column: id
            generator:
                strategy: AUTO
        name:
            column: '`name`'
            nullable: false
            type: string
            unique: true
        dataStorage:
            column: data_storage
            type: array
            nullable: true
        assetStorage:
            column: asset_storage
            type: array
            nullable: true
        creationDate:
            column: creation_date
            type: datetime
            nullable: false
    oneToMany:
        feeds:
            targetEntity: SocialDataBundle\Model\Feed
            orphanRemoval: true
            mappedBy: wall
            cascade:
                - all