SocialDataBundle\Model\Feed:
    attributes:
        id:
            groups: [Default, ExtJs]
        persistMedia:
            groups: [Default, ExtJs]
        publishPostImmediately:
            groups: [Default, ExtJs]
        configuration:
            groups: [Default, ExtJs]
        creationDate:
            groups: [Default, ExtJs]
        connectorEngine:
            groups: [Default, ExtJs]
        wall:
            groups: [Default]