
# Import Connector Specific Routes

connector_facebook:
    resource: '@SocialDataBundle/Resources/config/services/connector/facebook/routing.yml'

######### Core #########

# Admin Routes [Settings]

social_data_admin_settings_connectors:
    path: /admin/social-data/settings/get-connectors
    defaults: { _controller: SocialDataBundle\Controller\Admin\SettingsController::getConnectorsAction }

social_data_admin_settings_data_class_health_check:
    path: /admin/social-data/settings/data-class-health-check
    defaults: { _controller: SocialDataBundle\Controller\Admin\SettingsController::dataClassHealthCheckAction }

social_data_admin_settings_connector_install:
    path: /admin/social-data/settings/install-connector/{connectorName}
    defaults: { _controller: SocialDataBundle\Controller\Admin\SettingsController::installConnectorAction }

social_data_admin_settings_connector_uninstall:
    path: /admin/social-data/settings/uninstall-connector/{connectorName}
    defaults: { _controller: SocialDataBundle\Controller\Admin\SettingsController::uninstallConnectorAction }

social_data_admin_settings_change_connector_state:
    path: /admin/social-data/settings/change-connector-type/{connectorName}/{stateType}/{flag}
    defaults: { _controller: SocialDataBundle\Controller\Admin\SettingsController::changeConnectorStateAction }

social_data_admin_settings_save_connector_configuration:
    path: /admin/social-data/settings/save-connector-configuration/{connectorName}
    methods: [POST]
    defaults: { _controller: SocialDataBundle\Controller\Admin\SettingsController::saveConnectorConfigurationAction }

# Admin Routes [Walls]

social_data_admin_walls_fetch_walls:
    path: /admin/social-data/walls/fetch-walls
    methods: [GET]
    defaults: { _controller: SocialDataBundle\Controller\Admin\WallsController::fetchAllWallsAction }

social_data_admin_walls_fetch_wall:
    path: /admin/social-data/walls/fetch-wall
    methods: [GET]
    defaults: { _controller: SocialDataBundle\Controller\Admin\WallsController::fetchWallAction }

social_data_admin_walls_create_new_wall:
    path: /admin/social-data/walls/add-wall
    methods: [POST]
    defaults: { _controller: SocialDataBundle\Controller\Admin\WallsController::addWallAction }

social_data_admin_walls_delete_wall:
    path: /admin/social-data/walls/delete-wall/{wallId}
    methods: [POST]
    defaults: { _controller: SocialDataBundle\Controller\Admin\WallsController::deleteWallAction }

social_data_admin_walls_save_wall:
    path: /admin/social-data/walls/save-wall/{wallId}
    methods: [POST]
    defaults: { _controller: SocialDataBundle\Controller\Admin\WallsController::saveWallAction }

# Admin Routes [Logs]

social_data_admin_log_fetch_wall_logs:
    path: /admin/social-data/logs/fetch-wall-logs/{wallId}
    methods: [GET]
    defaults: { _controller: SocialDataBundle\Controller\Admin\LogController::loadLogsForWallAction }
