services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SocialDataBundle\Controller\Admin\SettingsController:
        calls:
            - [setContainer, ['@service_container']]

    SocialDataBundle\Controller\Admin\WallsController:
        calls:
            - [setContainer, ['@service_container']]

    SocialDataBundle\Controller\Admin\LogController:
        calls:
            - [setContainer, ['@service_container']]
