services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SocialDataBundle\EventListener\FeedPostListener:
        tags:
            - { name: kernel.event_subscriber }