services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SocialDataBundle\Repository\ConnectorEngineRepositoryInterface: '@SocialDataBundle\Repository\ConnectorEngineRepository'
    SocialDataBundle\Repository\ConnectorEngineRepository: ~

    SocialDataBundle\Repository\LogRepositoryInterface: '@SocialDataBundle\Repository\LogRepository'
    SocialDataBundle\Repository\LogRepository: ~

    SocialDataBundle\Repository\WallRepositoryInterface: '@SocialDataBundle\Repository\WallRepository'
    SocialDataBundle\Repository\WallRepository: ~

    SocialDataBundle\Repository\SocialPostRepositoryInterface: '@SocialDataBundle\Repository\SocialPostRepository'
    SocialDataBundle\Repository\SocialPostRepository: ~
