services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SocialDataBundle\Service\ConnectorServiceInterface: '@SocialDataBundle\Service\ConnectorService'
    SocialDataBundle\Service\ConnectorService: ~

    SocialDataBundle\Service\EnvironmentServiceInterface: '@SocialDataBundle\Service\EnvironmentService'
    SocialDataBundle\Service\EnvironmentService: ~

    SocialDataBundle\Service\StatisticServiceInterface: '@SocialDataBundle\Service\StatisticService'
    SocialDataBundle\Service\StatisticService: ~